<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ws_bootstrapthreefour"
 *
 * Auto generated by Extension Builder 2015-07-30
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Bootstrap 4 Basic',
	'description' => 'basic bootstrap 4 extension',
	'category' => 'distribution',
	'author' => 'Ulrich Diehl',
	'author_email' => 'mail@taunus-webservices.de',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.5.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.9.99',
            'fluid_styled_content' => ''
        ],
        'conflicts' => [],
    ],
);
